Update Sub cheker All.yml
ذاتتخ

diff --git a/. github/workflows/Sub cheker All.yml b/. github/workflows/Sub cheker All.yml
--- a/. github/workflows/Sub cheker All.yml
+++ b/. github/workflows/Sub cheker All.yml
@@ -3,8 +3,8 @@ name: Sub Checker All-in-One Synced
 on:
   workflow_dispatch:
   schedule:
-    - cron: "0 */12 * * *"   # اجرای shah10.py هر ۱۲ ساعت
-    - cron: "0 */24 * * *"   # اجرای shah20.py هر ۲۴ ساعت
+    - cron: "*/10 * * * *"   # اجرای cl10.py هر ۱۰ دقیقه
+    - cron: "*/20 * * * *"   # اجرای cl20.py هر ۲۰ دقیقه
     - cron: "0 0 * * *"   # غیرفعال کردن اجرای cl3.py
     - cron: "0 0 * * *"   # غیرفعال کردن اجرای cl4.py
 
@@ -13,8 +13,8 @@ permissions:
 
 jobs:
 
-  shah10-job:
-    name: Run shah10.py
+  cl10-job:
+    name: Run cl10.py
     runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
@@ -25,20 +25,20 @@ jobs:
       - run: pip install requests psutil retrying PyYaml || echo "skip install"
       - run: |
           rm -f final10.txt normal10.txt
-          timeout 180s python shah10.py || echo "❌ shah10.py failed or skipped"
+          timeout 180s python cl10.py || echo "❌ cl10.py failed or skipped"
       - run: |
           if [[ -s final10.txt || -s normal10.txt ]]; then
             git config user.name "github-actions[bot]"
             git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
             git add final10.txt normal10.txt
-            git commit -m "auto update from shah10.py [skip ci]" || echo "No changes"
+            git commit -m "auto update from cl10.py [skip ci]" || echo "No changes"
             git push || echo "skip push"
           else
             echo "⚠️ final10.txt یا normal10.txt خالی یا موجود نیست، commit نشد"
           fi
 
-  shah20-job:
-    name: Run shah20.py
+  cl20-job:
+    name: Run cl20.py
     runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
@@ -49,13 +49,13 @@ jobs:
       - run: pip install requests psutil retrying PyYaml || echo "skip install"
       - run: |
           rm -f final20.txt normal20.txt
-          timeout 300s python shah20.py || echo "❌ shah20.py failed or skipped"
+          timeout 300s python cl20.py || echo "❌ cl20.py failed or skipped"
       - run: |
           if [[ -s final20.txt || -s normal20.txt ]]; then
             git config user.name "github-actions[bot]"
             git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
             git add final20.txt normal20.txt
-            git commit -m "auto update from shah20.py [skip ci]" || echo "No changes"
+            git commit -m "auto update from cl20.py [skip ci]" || echo "No changes"
             git push || echo "skip push"
           else
             echo "⚠️ final20.txt یا normal20.txt خالی یا موجود نیست، commit نشد"
